### ISSUE TITLE
pectra-system-contracts-audit.md is missing links to appropriate PRs.

### ISSUE THREAD

**Issue by hacker-DOM** [ethereum/requests-for-proposals#19]
I'm not sure if this is the right place to mention it, but—the file [open-rfps/pectra-system-contracts-audit.md](https://github.com/ethereum/requests-for-proposals/blob/master/open-rfps/pectra-system-contracts-audit.md) says there are pull requests linked below, but they never are

In particular, it says:

> ## Audit Requirements

> The audit should focus **exclusively** on the smart contract bytecode, referenced in the pull requests below. 

The only repositories the document references are:

* [fjil/geas](https://github.com/fjl/geas)
* [lightclient/sys-asm](https://github.com/lightclient/sys-asm/pulls?q=is%3Apr)

sys-asm indeed has a [2935 pull request](https://github.com/lightclient/sys-asm/pull/19/files#diff-3c1b5b0f8de9e8a22e08a38dd56c9162b8df648ccd3e719c3dedfdc0667582e9), but I was not able to find 7002 and 7251

**Comment by Sophia-Gold** [comment]
The RFP links to the rendered EIPs on https://eips.ethereum.org/, which contain the bytecode, rather than the PRs.

**Comment by timbeiko** [comment]
[Fixed](https://github.com/ethereum/requests-for-proposals/commit/ce105b4592ea547ffb1c39256cfe2dd75a3a6d06), thanks for spotting @hacker-DOM :+1:
